### PR TITLE
Upload FCC_HK Logo

### PR DESCRIPTION
**Pull request by SWbottier**
FCC_HK Logo test#1 with svg file.

### CODE REVIEW

**Comment by gregorywong** [comment]
@SWbottier It doesn't look like it's rendering correctly on my computer. I've opened it using different methods, and the results look different. I'm guessing it's because the svg isn't compiling properly?

1. GitHub File viewer
screen shot 2017-09-18 at 1 47 11 pm

2. Inkscape
screen shot 2017-09-18 at 1 42 46 pm

3. Mac Finder previewer
screen shot 2017-09-18 at 1 43 07 pm

4. Including it on the html page (nothing shows)
screen shot 2017-09-18 at 1 44 38 pm

**Comment by SWbottier** [comment]
Yikes!!
okay let me upload a JPEG here as a comment first.
I've made way too many branches for this simple matter, need to find a way to resolve it all.

fcchk

**Comment by SWbottier** [comment]
This size is better i think

fcchk2

**Comment by gregorywong** [comment]
@SWbottier It doesn't seem like you uploaded the `.jpg` file. Did you `git add` the new file before committing and pushing?

**Comment by SWbottier** [comment]
I used "git commit -a -m "commit message" 
I thought this is a way to add and commit all changes.

**Comment by gregorywong** [comment]
@SWbottier 
You can use `git commit -a -m "commit message"` when your files have already been committed before. But if it's your first time committing the file (for example, a new file you created), you need to `add` it before committing.

**Comment by gregorywong** [comment]
Consolidated in #32 and merged already.

**Pull request closed without merging**
